name: cppcheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cppcheck-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - name: Install cppcheck
      run: sudo apt update && sudo apt install cppcheck

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Run cppcheck
      run: |
        cd cppcheck
        ./run.sh

  cppcheck-windows:

    runs-on: windows-latest

    steps:
    - name: Install cppcheck
      run: choco install cppcheck

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup cmake
      uses: lukka/get-cmake@latest

    - name: cmake p2pool
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022"

    - name: Run cppcheck
      run: |
        cd cppcheck
        ./run.cmd
