name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cppcheck-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - name: Install cppcheck
      run: sudo apt update && sudo apt install cppcheck

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Run cppcheck
      run: |
        cd cppcheck
        ./run.sh
